### ISSUE TITLE
--verbose --headers vs. --headers --verbose

### ISSUE THREAD

**Issue by silverwind** [jakubroztocil/httpie#287]
`--verbose --headers` doesn't print the request headers, while `--headers --verbose` does. I think the ordering of arguments shouldn't matter in this case, and request headers should always be printed with --verbose.

**Comment by jakubroztocil** [comment]
@silverwind It's slightly counterintuitive in this case, but it's an intended behaviour and it's documented here: https://github.com/jakubroztocil/httpie#output-options

`--headers, -h`, `--body, -b`, and `--verbose, -v` are just aliases for `--print=<arg>`. And when you repeat an argument (which you in fact do here because both `--headers` and `--verbose` are treated as `--print=<arg>`), then the value specified last wins:

1. `http --verbose --headers `  (what you specify)
2. `http --print=hbHB --print=h` (what HTTPie sees)
3. `http --print=h` (how it interprets)

**Comment by silverwind** [comment]
Thanks for the detailed explanation. Still strikes me as odd that `--verbose` actually makes it print *less* information.
