### ISSUE TITLE
SPDY support?

### ISSUE THREAD

**Issue by jarmo** [jakubroztocil/httpie#292]
Cannot find anything related with `spdy`. Does `httpie` not support it?

**Comment by sigmavirus24** [comment]
`requests` does not support SPDY, nor does it have any plans to add that support in the coming months (or year as best we can tell). Since `httpie` uses `requests`, it does not support SPDY either. There is a pure-python SPDY implementation but it's no longer supported. There's also a pure-python HTTP/2 implementation over at [hyper](/Lukasa/hyper).

**Comment by jakubroztocil** [comment]
@jarmo as @sigmavirus24 has pointed out, `requests` currently lacks SPDY support. And HTTPie will support it  as soon as it lands in `requests`.

**Comment by sigmavirus24** [comment]
>  as soon as it lands in requests

There aren't currently plans for it, so don't be surprised if it doesn't ever land.
