### ISSUE TITLE
Cannot send json array

### ISSUE THREAD

**Issue by asunar** [jakubroztocil/httpie#350]
Trying out an example from the usage section on windows 8. Getting the following error.
What am I doing wrong here? Python version 3.4.3

![httpie](https://cloud.githubusercontent.com/assets/204049/7478759/639a7086-f322-11e4-8e8e-437a7e9edb0a.png)

**Comment by jakubroztocil** [comment]
The problem is with how the shell interprets `'` and `"`. It looks like with `cmd.exe` (which I believe you use)  you need to manually use `\` to escape the nested `"` despite the string being wrapped in a pair of `'`:

```bash
http httpbin.org/post hobbies:='[\"http\", \"pies\"]'
```

I'm not very familiar with `cmd.exe` so there might be an easier way to pass literal `"` characters.

**Comment by asunar** [comment]
Two double-quotes inside double quotes worked for me.
![double_double_quotes](https://cloud.githubusercontent.com/assets/204049/7576581/ef64cf9e-f804-11e4-9514-fe6d3e9000f0.png)

**Comment by jakubroztocil** [comment]
Ok, good to know!
