### ISSUE TITLE
Project name makes me sad

### ISSUE THREAD

**Issue by lorenzos** [jakubroztocil/httpie#361]
My mind keeps reading **HTTPie** as **HTTP-Internet-Explorer**, and this makes me feel sad.

**Comment by jakubroztocil** [comment]
Yeah. The original name was *HTTPet* (HTTP + pet), but after a couple of days I renamed it to *HTTPie* because I thought it was smart and didn't realize the possible confusion with something that has to do with IE.

The etymology behind the name *HTTPie* is the following:

a) HTTP as easy as 🍰 
b) HTTP 🐍 –powered

I guess we could start calling it *HTT🍰*  or *HTT🐍* to prevent that confusion 😉
