### ISSUE TITLE
Hangs on Git Bash

### ISSUE THREAD

**Issue by decadence** [jakubroztocil/httpie#612]
httpie is working ok on Windows cmd but just hangs on Git Bash.
Though http without args finds command.
![screenshot_1](https://user-images.githubusercontent.com/1434668/30689927-3c0d0bb2-9ecb-11e7-92d2-7791dc11c7f3.png)
![screenshot_2](https://user-images.githubusercontent.com/1434668/30689929-3c13283a-9ecb-11e7-8a61-6e771e051475.png)
![screenshot_3](https://user-images.githubusercontent.com/1434668/30689928-3c0e86fe-9ecb-11e7-97c7-5e3834bbbb16.png)

**Comment by jwedel** [comment]
Same issue here...
- Works in CMD/PowerShell
- Works with `--ignore-stdin` but does not output the headers....

**Comment by jakubroztocil** [comment]
This is, unfortunately, a bug in Git Bash. It makes Python think that both `stdin` and `stdout` are redirected. And since HTTPie changes its behaviour when data is piped in/out, it causes these issues.

As a workaround, you can try change the `default_options` in your `config.json` to ignore `stdin` redirection and make HTTPie behave for redirected `stdout` similarly to the default mode :

```json5
{
    // […]
    "default_options": [
        "--ignore-stdin",
        "--print=hb", 
        "--pretty=all"
    ],
}
```

(To see the location of the config file, run `http --debug` and look for `config_dir`.)

See the docs for more details about how piping changes HTTPie's behaviour:

https://httpie.org/doc#redirected-input
https://httpie.org/doc#redirected-output
